### ISSUE TITLE
Optimize finding the brightest MOS mode

### ISSUE THREAD

**Issue by inthar-raven** [xenharmonic-devs/moment-of-symmetry#20]
(Creating a separate issue for this) Maybe we can optimize Björklund's algorithm to run in logarithmic time, since it works via a similar principle to Euclid's algorithm.

**Comment by frostburn** [comment]
Could certainly be possible. Just needs benchmarks to verify that a new implementation is faster on realistic cases instead of just above size 1000 or something.
